### DISCUSSION TITLE
chance that killing the dragon places an egg

### DISCUSSION THREAD

**Discussion by hirata-estate** [PurpurMC/Purpur#1004] [Feature Requests]
An extension of entities.behavior.ender-dragons-death-always-places-dragon-egg in paper.yml.

```
world-settings:
  default:
    mobs:
      ender_dragon:
        egg-spawn-chance: 0.25 (0.00 by default)
```
