### DISCUSSION TITLE
Join/Leave broadcasts radius option

### DISCUSSION THREAD

**Discussion by Pantera07** [PurpurMC/Purpur#1171] [__Dismissed__] [answered]
Add the option to view only nearby player join/leave messages.

default config example:
```
settings:
  broadcasts:
    join:
      broadcast-radius: 0
    leave:
      broadcast-radius: 0
```
