### DISCUSSION TITLE
Crossbows with infinity work with effect arrows

### DISCUSSION THREAD

**Discussion by alechretien16** [PurpurMC/Purpur#1313] [Feature Requests]
I would expect this to apply to the crossbow equally, not just the bow.

The "Infinity-Bow" behavior options in purpur.yml only apply to the bow, as specified, it should be crossbow compatible.

By enabling the option for crossbows to be compatible with the infinity enchantment, this makes it so that arrows from rockets or arrows with effects are not spent, even if those options are set to "false" in the purpur.yml file ("infinity-bow:"), I don't know if it's a bug but it would be great if this wasn't the case.

Options on purpur.yml
```yml
  enchantment:
    allow-infinity-and-mending-together: true
    allow-infinity-on-crossbow: true
    allow-looting-on-shears: true
    allow-transparent-blocks-in-enchantment-box: false

      infinity-bow:
        works-without-arrows: true
        normal-arrows: true
        spectral-arrows: false
        tipped-arrows: false
```
