### DISCUSSION TITLE
Option to allow dispensers to plant seeds

### DISCUSSION THREAD

**Discussion by A-z-z-y** [PurpurMC/Purpur#1475] [__Dismissed__] [answered]
This may fit better with PurpurExtras since that plugin has some stuff with dispensers, but I digress.

This option would allow dispensers on any side, or on top, of an empty air block above a block of farmland to be planted with seeds within the dispenser when the dispenser is powered.

This would allow for full farming automation, which would probably be quite handy for many folks :)

```yaml
...
dispenser:
    break-blocks:
      pickaxe: true
      shovel: true
      hoe: true
      axe: true
      shears: true
    shears-shear-pumpkin: true
    puts-discs-in-jukebox: true
    interact-with-cauldron: true
    plant-seeds: true # The new option
...
```

**Comment by granny** [comment, marked as answer]
Definitely could be a PurpurExtras feature. Having it as an option in PurpurExtras would allow it to build off of what's already been done. This idea could be abstracted as an `interact-blocks` option that includes all the same tools as `break-blocks` as well as `hand`

```yaml
dispenser:
    interact-blocks:
      pickaxe: true
      shovel: true
      hoe: true
      axe: true
      shears: true
      hand: true
```
