### DISCUSSION TITLE
Temporally wake up lobotomized villagers when interacted

### DISCUSSION THREAD

**Discussion by AllayBreeze** [PurpurMC/Purpur#1503] [Feature Requests]
Add an option to make lobotomized villagers regain their AI for a short time when players right click on them. A configuration may be:
```
lobotomize:
  wake-up-when-interacted:
    enabled: true
    ticks: 20
```
This can bring two benefits (and maybe more): If the villager gets lobotomized unexpectedly (for example they haven't got their jobs), this can help with solving these problems without opening a road to wake them; And it can make villagers looking at players right clicking on them, bringing them a bit more living feels.
