### DISCUSSION TITLE
Disabling/enabling certain entities collision.

### DISCUSSION THREAD

**Discussion by Agaloth** [PurpurMC/Purpur#433] [Feature Requests]
## Is your feature request related to a problem?
  For certain cases, players want villagers to have collisions for farms or another type of farms but it's not possible due to the collision disabling it on all entities.

## Describe the solution you'd like.

  A similar system as SugarcaneMC, they did another way but I'm fairly certain it could be implemented better:

```
    collisions:
      players: false
      animals: false
      ambient: false
      monsters: false
      villagers: false
      pillagers: false
      iron-golems: false
      misc: false
      items: false
      water-creature: false
      water-ambient: false
```
