### DISCUSSION TITLE
Configurable size for Phantoms (& more ?)

### DISCUSSION THREAD

**Discussion by craftish37** [PurpurMC/Purpur#441] [__Completed__] [answered]
Like some other mobs, the phantom has a size tag which, if configurable, can result in cool events (:

I think a spawn size range will be the most appropriate as below:

size: minsize - maxsize

Of course, as for slimes, the number of HP of the phantom could vary according to its size (parameter apart)

use-size-as-max-health:
  max_health: size * size    <--or something like this

I don't really know how you could do that, I don't know much about java yet, but I hope this feature will be possible to the chagrin of some players >:}

**Comment by BillyGalbreath** [comment, marked as answer]
Implemented in build 1514

https://github.com/PurpurMC/Purpur/commit/930084af05a1795c86af153e5051fc7354650f59

The following settings are Strings and can contain `size` for the entity's size. Defaults represent vanilla behavior.

```yaml
world-settings:
  magma_cube:
    attributes:
      max_health: size
      attack_damage: size * size
  phantom:
    attributes:
      max_health: '20.0'
      attack_damage: 6 + size
  slime:
    attributes:
      max_health: size
      attack_damage: size * size
```

Phantom sizes can be between 0 and 64. Default value of 0 is vanilla behavior
```yaml
world-settings:
  phantom:
    size:
      min: 0
      max: 0
```
