### DISCUSSION TITLE
Some suggestions for tool interactions with various blocks

### DISCUSSION THREAD

**Discussion by Keeg-Turner** [PurpurMC/Purpur#449] [__Completed__] [answered]
My suggestions are as follows:

- Add options to make grass blocks drop seeds when a hoe and/or shovel is used on them (a nod to the pre-beta 1.6 days)
- Add options to make mycelium drop brown and/or red mushrooms when a hoe and/or shovel is used on it
- Add option to make podzol drop spruce saplings when a hoe and/or shovel is used on it
- Add options to make logs/wood have a chance to drop paper upon being stripped (like this [data pack](http://mc.voodoobeard.com/#paperbark))
- Add options to use a hoe on mossy cobblestone, mossy stone bricks, and infested mossy stone bricks to turn them into their non-mossy equivalents, and additional options to give these blocks a chance to drop moss carpet and/or vines upon doing this
- Add an option to expand the amount of blocks that can be turned into farmland (equivalent to the one that already existed for dirt paths)

To summarize, I'd recommend implementing the default settings like so (I tried to follow the `purpur.yml` format as closely as possible, but there may still be a better way to organize these):

```yml
world-settings:
  default:
    blocks:
      grass_block:
        using-hoe-drops-seeds-chance: 0.0
        using-shovel-drops-seeds-chance: 0.0
      mycelium:
        using-hoe-drops-brown-mushroom-chance: 0.0
        using-hoe-drops-red-mushroom-chance: 0.0
        using-shovel-drops-brown-mushroom-chance: 0.0
        using-shovel-drops-red-mushroom-chance: 0.0
      podzol:
        using-hoe-drops-spruce-sapling-chance: 0.0
        using-shovel-drops-spruce-sapling-chance: 0.0
      oak_log:
        stripping-drops-paper-chance: 0.0
      spruce_log:
        stripping-drops-paper-chance: 0.0
      birch_log:
        stripping-drops-paper-chance: 0.0
      jungle_log:
        stripping-drops-paper-chance: 0.0
      acacia_log:
        stripping-drops-paper-chance: 0.0
      dark_oak_log:
        stripping-drops-paper-chance: 0.0
      crimson_stem:
        stripping-drops-paper-chance: 0.0
      warped_stem:
        stripping-drops-paper-chance: 0.0
      oak_wood:
        stripping-drops-paper-chance: 0.0
      spruce_wood:
        stripping-drops-paper-chance: 0.0
      birch_wood:
        stripping-drops-paper-chance: 0.0
      jungle_wood:
        stripping-drops-paper-chance: 0.0
      acacia_wood:
        stripping-drops-paper-chance: 0.0
      dark_oak_wood:
        stripping-drops-paper-chance: 0.0
      crimson_hyphae:
        stripping-drops-paper-chance: 0.0
      warped_hyphae:
        stripping-drops-paper-chance: 0.0
      mossy_cobblestone:
        hoe-removes-moss: false
        using-hoe-drops-moss-carpet-chance: 0.0
        using-hoe-drops-vines-chance: 0.0
      mossy_stone_bricks:
        hoe-removes-moss: false
        using-hoe-drops-moss-carpet-chance: 0.0
        using-hoe-drops-vines-chance: 0.0
      infested_mossy_stone_bricks:
        hoe-removes-moss: false
        using-hoe-drops-moss-carpet-chance: 0.0
        using-hoe-drops-vines-chance: 0.0
    gameplay-mechanics:
      hoe-turns-block-to-farmland:
      - minecraft:dirt
      - minecraft:grass_block
      - minecraft:dirt_path
```
