### DISCUSSION TITLE
Add configuration for enchantment application

### DISCUSSION THREAD

**Discussion by MartijnMuijsers** [PurpurMC/Purpur#678] [__Dismissed__] [answered]
A configuration option like follows:

```yaml
allowed_enchantment_changes:
  anvil:
  - type: ELYTRA
    enchantment: MENDING
    result: deny
  - type: BOW
    enchantment: LOOTING
    result: allow
  - type: *
    enchantment: CURSE_OF_VANISHING
    result: allow
  enchantment_table: []
  villager_trade: []
  generated_loot:
  - type: GOLDEN_SHOVEL
    enchantment: FIRE_ASPECT
    result: allow
```

If I were to submit a PR for this, would it be accepted?

**Comment by sph432** [comment]
How should this handle accepted and unaccepted enchant combos?
Be advised that we already have:
```yml
settings:
   ...
  enchantment:
    allow-infinity-and-mending-together: true
    allow-infinity-on-crossbow: true
    allow-unsafe-enchants: true
```

Modifying base item attributes in a similar manner would be awesome as well.
