### DISCUSSION TITLE
Make grindstones remove extra NBT data.

### DISCUSSION THREAD

**Discussion by hirata-estate** [PurpurMC/Purpur#738] [Feature Requests]
Make grindstones remove extra NBT data, e.g. items being Unbreakable, their lore, their attributes, etc.

```
grindstone:
  ignore-curses: true
  remove-nbt: true/false
```

or

```
grindstone:
  ignore-curses: true
  remove:
    enchantments: true
    attributes: false
    lore: false
    unbreakable: false
    flags: false (adventure mode rules)
```
