### DISCUSSION TITLE
Mobs ignore players wearing their head.

### DISCUSSION THREAD

**Discussion by hirata-estate** [PurpurMC/Purpur#750] [__Completed__] [answered]
Mobs ignore players wearing their head.
Config option for zombies, creepers, skeletons, wither skeletons & dragons.
```
mobtype:
 ignore-wearing-head: bool
 ```
 
 Very optional; head tags.
 ```
mobtype:
 ignore-wearing-head: bool
 skull:
  uuid: 
  - 853c80ef-3c37-49fd-aa49-938b674adae6
  - some.other.uuid
  texture: 
  - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTM4OWUwZDVkM2U4MWY4NGI1NzBlMjk3ODI0NGIzYTczZTVhMjJiY2RiNjg3NGI0NGVmNWQwZjY2Y2EyNGVlYyJ9fX0=
```
