### DISCUSSION TITLE
Option to disable spawner change on mob egg interact.

### DISCUSSION THREAD

**Discussion by mibby** [PurpurMC/Purpur#839] [__Dismissed__] [answered]
Would it be possible to add an option to disable being able to change spawners with mob eggs? This is a vanilla feature and I provide players a way to obtain eggs. However I do not want them to be able to use the egg on a spawner with the silk touch patch to have passive spawners for mobs like pigs. I would rather outright disable the ability to change spawners on interact if they don't have permission to do so.

Finding a separate plugin for this seems a bit excessive since it's more of a smaller thing.

**Comment by BillyGalbreath** [comment, marked as answer]
Paper already has this option in paper.yml

```yaml
world-settings:
  default:
    game-mechanics:
      disable-mob-spawner-spawn-egg-transformation: false
```
