### DISCUSSION TITLE
Seed for dungeons (monster rooms)

### DISCUSSION THREAD

**Discussion by cocosunriseidk** [PurpurMC/Purpur#860] [__Dismissed__] [answered]
There is possible to change the seed for different structures in the purpur.yml config, but not for monster rooms. It would be very nice to see such a function, because [there are programs](https://github.com/WearBlackAllDay/SeedCandy) that allow you to find out the world's seed by the mossy cobblestone of these dungeons. 
```
  seed: 
    structure:
      buried_treasure: -1
      mineshaft: -1
      stronghold: -1
      monster_room: 197039781
```
