### DISCUSSION TITLE
Block blast resistance configuration

### DISCUSSION THREAD

**Discussion by MelnCat** [PurpurMC/Purpur#928] [Feature Requests]
It would be cool if there was a way to change the blast resistance of blocks in the config.
Maybe something like
```yaml
blast-resistance-overrides:
    diamond_block: 3000
    obsidian: 6
```
Or something similar
